export const EVENTS_PER_INSTALL_MAX = 120
export const EVENTS_PER_INSTALL_WINDOW_MS = 60 * 1000

export const EVENTS_PER_ADDRESS_MAX = 600
export const EVENTS_PER_ADDRESS_WINDOW_MS = 60 * 1000

export const ERASURE_PER_INSTALL_MAX = 5
export const ERASURE_PER_INSTALL_WINDOW_MS = 60 * 60 * 1000

export const ERASURE_PER_ADDRESS_MAX = 30
export const ERASURE_PER_ADDRESS_WINDOW_MS = 60 * 60 * 1000

export const INSTALLS_PER_ADDRESS_MAX = 30
export const INSTALLS_PER_ADDRESS_WINDOW_MS = 60 * 1000
